apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: f5-gslb-pacman
  labels:
    app.kubernetes.io/name: f5-gslb-pacman
spec:
  # Added for f5 demonstration
  host: pacman-acm-ansible-app.apps.cluster-45k5t.45k5t.sandbox996.opentlc.com/
  path: "/"
  to:
    kind: Service
    name: pacman
